spring.output.ansi.enabled= ALWAYS

spring.application.name=lab8
spring.datasource.url=jdbc:postgresql://localhost:5432/lab8demo
spring.datasource.username=postgres
spring.datasource.password=adminomg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
